---
title: "hai-project"
output: html_document
---

```{r setup, include=FALSE}
library(DataExplorer)
library(tidyverse)
library(dplyr)
library(ggplot2)
```

## R Markdown

EDA reports for main dfs
```{r}
create_report(MICROBIOLOGYEVENTS)
create_report(CHARTEVENTS)
create_report(ADMISSIONS)
create_report(PATIENTS)
```

```{r}
admissions <- as_data_frame(ADMISSIONS)
microbio_events <- as_data_frame(MICROBIOLOGYEVENTS)
patients <- as_data_frame(PATIENTS)
```

```{r}
demographics <- merge.data.frame(admissions, patients, by = "subject_id")
demographics
```
Number of rows
```{r}
nrow(demographics)
```

Number of distinct rows
```{r}
nrow(distinct(demographics))
```

Clean up demographics data
```{r}
demographics %>% 
  mutate(age = floor((dod-dob)/365)) %>%  #label is days (is in years), 9 people are >=300 years old?
  filter(age < 300) %>% 
  select(subject_id, insurance, religion, ethnicity, gender, age) %>% 
  distinct() -> cleaner_demographics

cleaner_demographics
```
Create report for cleaned-up demographic data
```{r}
create_report(cleaner_demographics)
```

Look at microbiological events data
```{r}
microbio_events %>% 
  select(subject_id, hadm_id, spec_itemid, spec_type_desc, org_name, ab_name, interpretation)
```

Filter out only people who have been tested for MRSA
```{r}
microbio_events %>% 
  select(subject_id, hadm_id, spec_itemid, spec_type_desc, org_name, ab_name, interpretation) %>%
  filter(spec_itemid == "70091") -> mrsa_only
mrsa_only
```
Unique MRSA tests
```{r}
microbio_events %>% 
  filter(spec_itemid == "70091") %>% 
  summarise(total_unique_mrsa_test = unique(hadm_id)) 
```

Unique tests for MRSA that were positive
```{r}
mrsa_only %>% 
  filter(grepl("positive", org_name, ignore.case = T) == T) %>% 
  summarise(total_unique_mrsa_positive = unique(hadm_id))
```

```{r}
merged_adm_mbevent <- merge.data.frame(admissions, microbio_events, by = "hadm_id")
merged_adm_mbevent %>% 
   select(hadm_id, spec_itemid, spec_type_desc, org_name, ab_name, diagnosis, interpretation) %>%
  filter(spec_itemid == "70091")
```


```{r}
chart_events <- as_data_frame(CHARTEVENTS)
glimpse(chart_events)
```

```{r}
chart_events %>% 
  
```



